# Generated by Django 4.2.2 on 2023-07-01 12:01
import os
from django.db import connection
from django.db import migrations, models


def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), 'insert.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)

class Migration(migrations.Migration):

    dependencies = [
        ('bincomApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('uniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
