# Generated by Django 4.2.2 on 2023-07-01 21:38

import os
from django.db import connection
from django.db import migrations, models

def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), 'insert.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)

class Migration(migrations.Migration):

    dependencies = [
        ('bincomApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
